[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools", "python312Packages.wheel"]

[phases.install]
cmds = ["./build.sh"]

[phases.build]
cmds = ["python manage.py migrate --noinput"]

[start]
cmd = "gunicorn project_settings.wsgi:application --bind 0.0.0.0:$PORT --workers 3"