[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PYTHONPATH = "/app"
DJANGO_SETTINGS_MODULE = "project_settings.settings"
