# Generated by Django 5.1.6 on 2025-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api1", "0009_remove_age_priority_fields"),
        ("api1", "0009_service_sitesettings_feedbackrequest"),
    ]

    operations = []
