# Generated by Django 5.1.6 on 2025-06-18 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api1", "0012_merge_20250618_0755"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterDailySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "work_start_time",
                    models.TimeField(
                        default="09:00:00", verbose_name="Начало рабочего дня"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default="17:00:00", verbose_name="Конец рабочего дня"
                    ),
                ),
                (
                    "slot_duration",
                    models.DurationField(
                        default="02:00:00", verbose_name="Длительность слота"
                    ),
                ),
                (
                    "max_slots",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Максимум слотов в день"
                    ),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=True, verbose_name="Рабочий день"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки к дню")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master",
                    models.ForeignKey(
                        limit_choices_to={"role": "master"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Мастер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание дня мастера",
                "verbose_name_plural": "Расписания дней мастеров",
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master", "date"), name="unique_master_daily_schedule"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_date", models.DateField(verbose_name="Дата слота")),
                ("slot_time", models.TimeField(verbose_name="Время слота")),
                (
                    "slot_number",
                    models.PositiveIntegerField(verbose_name="Номер слота в дне"),
                ),
                (
                    "slot_duration",
                    models.DurationField(
                        default="02:00:00", verbose_name="Длительность слота"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Зарезервирован"),
                            ("confirmed", "Подтвержден"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="reserved",
                        max_length=20,
                        verbose_name="Статус слота",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки к слоту")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master",
                    models.ForeignKey(
                        limit_choices_to={"role": "master"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot",
                        to="api1.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот заказа",
                "verbose_name_plural": "Слоты заказов",
                "ordering": ["slot_date", "slot_time", "slot_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("master", "slot_date", "slot_number"),
                        name="unique_master_daily_slot",
                    )
                ],
            },
        ),
    ]
