# Generated by Django 5.1.6 on 2025-06-18 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api1", "0013_masterdailyschedule_orderslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdailyschedule",
            name="slot_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200),
                verbose_name="Длительность слота",
            ),
        ),
        migrations.AlterField(
            model_name="orderslot",
            name="slot_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=7200),
                verbose_name="Длительность слота",
            ),
        ),
    ]
