# Generated by Django 5.1.6 on 2025-07-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api1", "0014_alter_masterdailyschedule_slot_duration_and_more"),
        ("api1", "0014_update_work_schedule_to_21_hours"),
    ]

    operations = []
