# Generated by Django 5.2 on 2025-06-03 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('в обработке', 'В обработке'), ('назначен', 'Назначен мастеру'), ('выполняется', 'Выполняется'), ('ожидает_подтверждения', 'Ожидает подтверждения'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен')], default='новый', max_length=25),
        ),
        migrations.CreateModel(
            name='OrderCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(verbose_name='Описание выполненных работ')),
                ('completion_photos', models.JSONField(blank=True, default=list, verbose_name='Фотографии выполненных работ')),
                ('parts_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расходы на запчасти (₸)')),
                ('transport_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Транспортные расходы (₸)')),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная сумма получена за заказ (₸)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общие расходы (₸)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая прибыль (₸)')),
                ('completion_date', models.DateTimeField(verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('ожидает_проверки', 'Ожидает проверки'), ('одобрен', 'Одобрен'), ('отклонен', 'Отклонен')], default='ожидает_проверки', max_length=20, verbose_name='Статус')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('curator_notes', models.TextField(blank=True, null=True, verbose_name='Заметки куратора')),
                ('is_distributed', models.BooleanField(default=False, verbose_name='Средства распределены')),
                ('curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'curator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_completions', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(blank=True, limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='api1.order')),
            ],
            options={
                'verbose_name': 'Завершение заказа',
                'verbose_name_plural': 'Завершения заказов',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order_completion', 'Завершение заказа'), ('master_payment', 'Выплата мастеру'), ('curator_payment', 'Выплата куратору'), ('company_income', 'Доход компании'), ('master_deferred', 'Отложенная выплата мастеру')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('order_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api1.ordercompletion')),
            ],
            options={
                'verbose_name': 'Финансовая транзакция',
                'verbose_name_plural': 'Финансовые транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
