# Generated by Django 5.2 on 2025-06-05 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_profitdistributionsettings_company_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('settings_updated', 'Настройки обновлены'), ('percentage_settings_updated', 'Настройки процентов обновлены'), ('company_balance_updated', 'Баланс компании обновлён'), ('system_maintenance', 'Системное обслуживание'), ('user_role_changed', 'Роль пользователя изменена'), ('backup_created', 'Резервная копия создана'), ('data_import', 'Импорт данных'), ('data_export', 'Экспорт данных')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Системный лог',
                'verbose_name_plural': 'Системные логи',
                'ordering': ['-created_at'],
            },
        ),
    ]
