# Generated by Django 5.2 on 2025-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип оборудования'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('наличные', 'Наличные'), ('карта', 'Банковская карта'), ('перевод', 'Банковский перевод'), ('элсом', 'Элсом'), ('mbанк', 'МБанк')], default='наличные', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('низкий', 'Низкий'), ('обычный', 'Обычный'), ('высокий', 'Высокий'), ('срочный', 'Срочный')], default='обычный', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Акции'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип услуги'),
        ),
    ]
