# Generated by Django 5.2 on 2025-06-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0006_masterprofitsettings'),
        ('api1', '0006_remove_order_fields'),
    ]

    operations = [
    ]
