# Generated by Django 5.1.6 on 2025-06-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0008_alter_masterprofitsettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='age',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priority',
        ),
    ]
