# Generated by Django 5.1.6 on 2025-06-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api1", "0010_merge_20250617_1119"),
        ("api1", "0011_add_master_balance_total_transaction_type"),
    ]

    operations = []
